In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt


In [4]:
import seaborn as sns

In [6]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Womens Clothing E-Commerce Reviews.csv')

In [7]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [10]:
df.shape

(23486, 11)

In [11]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [12]:
df[df['Review Text']==""]=np.NaN

In [13]:
df['Review Text'].fillna("No Review",inplace=True)

In [14]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [15]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

In [17]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [18]:
X=df['Review Text']

In [19]:
Y=df['Rating']

In [21]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.7,random_state=2529,stratify=Y)

In [24]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv=CountVectorizer(lowercase=True, analyzer='word',stop_words='english',max_features=5000)

In [27]:
X_train_cv=cv.fit_transform(X_train)

In [28]:
cv.get_feature_names_out()

array(['00', '00p', '0p', ..., 'zipping', 'zips', 'zoom'], dtype=object)

In [44]:
X_train.to_numpy()

array(["I really like this blouse. you could wear it tucked, but the pleats would disappear. my only complaint is that it's a bit too full round the waist. it would be a good choice for thanksgiving dinner!",
       'Bought these online - sale, and am really happy with them. soft and light material - feel breezy, like a beach pant should!',
       'This dress is made well and fit nice. i am 64" and 135 lbs. i really wanted it keep it but it is going back. the colors in person are much more muted and with my pale blonde hair and fair skin the color was all wrong.',
       ...,
       "I ordered a petite small. i'm 5'3, 135 lbs and 34b and the length was perfect and the fit was great. like the previous reviews. love you can wear a bra with it.",
       "I was really excited to see what this looked like in person. when i unpacked this shirt i was shocked to see what how short it looked. the colors are very close to what you see online but the shirt is super boxy. i have a smaller torso an

In [40]:
X_test=cv.fit_transform(X_test)

In [41]:
cv.get_feature_names_out()

array(['00', '00p', '0p', ..., 'zips', 'zone', 'zoom'], dtype=object)

In [42]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [45]:
from sklearn.naive_bayes import MultinomialNB

In [46]:
model=MultinomialNB()

In [47]:
model.fit(X_train_cv,Y_train)

MultinomialNB()

In [48]:
y_pred=model.predict(X_test)

In [50]:
y_pred.shape

(7046,)

In [51]:
y_pred

array([1, 1, 5, ..., 4, 1, 1])

In [52]:
model.predict_proba(X_test)

array([[9.99999717e-01, 2.83060727e-07, 9.09037439e-11, 8.95906582e-11,
        8.12789515e-13],
       [9.99877356e-01, 1.22571197e-04, 7.55789788e-09, 5.27049704e-09,
        6.02753154e-08],
       [2.08334396e-02, 3.66889912e-02, 1.32649382e-01, 2.21432063e-01,
        5.88396125e-01],
       ...,
       [6.98212628e-02, 1.25105379e-01, 1.88786739e-01, 5.35701477e-01,
        8.05851423e-02],
       [9.88993706e-01, 1.10062934e-02, 6.50175680e-10, 2.32505543e-10,
        1.99873299e-18],
       [9.89987944e-01, 8.27601623e-03, 1.16681214e-05, 1.72315213e-03,
        1.21995118e-06]])

In [53]:
from sklearn.metrics import confusion_matrix,classification_report

In [56]:
print(confusion_matrix(Y_test,y_pred))

[[ 224   10    0    2   17]
 [ 423   30    1    6   10]
 [ 784   33    9    5   30]
 [1381   43    6   16   77]
 [3516  120   41   28  234]]


In [58]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           1       0.04      0.89      0.07       253
           2       0.13      0.06      0.08       470
           3       0.16      0.01      0.02       861
           4       0.28      0.01      0.02      1523
           5       0.64      0.06      0.11      3939

    accuracy                           0.07      7046
   macro avg       0.25      0.21      0.06      7046
weighted avg       0.45      0.07      0.08      7046



In [59]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [60]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [61]:
y=df['Rating']

In [62]:
X=df['Review Text']

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,train_size=0.7,random_state=2529,stratify=y)

In [65]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [68]:
X_train_cv=cv.fit_transform(X_train)

In [69]:
X_test=cv.fit_transform(X_test)

In [70]:
from sklearn.naive_bayes import MultinomialNB

In [71]:
model=MultinomialNB()

In [72]:
model.fit(X_train_cv,Y_train)

MultinomialNB()

In [73]:
y_pred=model.predict(X_test)

In [74]:
y_pred.shape

(7046,)

In [75]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [76]:
from sklearn.metrics import confusion_matrix,classification_report

In [77]:
print(confusion_matrix(Y_test,y_pred))

[[ 449 1134]
 [ 989 4474]]


In [79]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.31      0.28      0.30      1583
           1       0.80      0.82      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.69      7046

